#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_box3d = env_modules.Clone()
env_box3d.Prepend(CPPPATH=["#thirdparty/box3d/include"])
env_box3d.Append(CPPDEFINES=["BOX3D_DISABLE_AVX2"])

# Isolate the solver and adapter from global fast math and FMA contraction flags.
for key in ("CCFLAGS", "CFLAGS", "CXXFLAGS"):
    env_box3d[key] = [flag for flag in env_box3d[key] if not str(flag).startswith(("/fp:", "-ffast-math", "-Ofast", "-ffp-contract=", "-funsafe-math-optimizations"))]
if env.msvc:
    env_box3d.Append(CCFLAGS=["/fp:precise"])
    if env["use_llvm"]:
        env_box3d.Append(CCFLAGS=["/clang:-ffp-contract=off"])
else:
    env_box3d.Append(CCFLAGS=["-fno-fast-math", "-ffp-contract=off"])
    if env["platform"] not in ("macos", "ios", "windows", "web"):
        env.AppendUnique(LIBS=["m"])

env_thirdparty = env_box3d.Clone()
env_thirdparty.disable_warnings()
thirdparty_obj = []
env_thirdparty.add_source_files(thirdparty_obj, "#thirdparty/box3d/src/*.c")
env.modules_sources += thirdparty_obj

module_obj = []
env_box3d.Prepend(CPPPATH=["#modules/box3d/scene_backend"])
env_box3d.add_source_files(module_obj, "*.cpp")
for directory in ("", "joints/", "misc/", "objects/", "servers/", "shapes/", "spaces/"):
    env_box3d.add_source_files(module_obj, "scene_backend/" + directory + "*.cpp")
env.modules_sources += module_obj
env.Depends(module_obj, thirdparty_obj)
