# Complete a previously built .NET editor using its actual SCons configuration.
$ErrorActionPreference = 'Stop'
$projectRoot = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot '../..'))
$python = Join-Path $projectRoot '.build/venv/Scripts/python.exe'
Push-Location $projectRoot
try {
    $buildInfo = & $python -c 'import json; e=json.load(open(".scons_env.json")); print(json.dumps({k:e[k] for k in ("target", "module_mono_enabled", "PROGSUFFIX", "precision", "deprecated")}))' | ConvertFrom-Json
    if ($LASTEXITCODE -ne 0) { throw 'Could not read the completed build configuration.' }
    if (-not $buildInfo.module_mono_enabled) { return }
    if ($buildInfo.target -ne 'editor') { throw 'Managed glue must be generated by an editor build.' }
    $editor = Join-Path $projectRoot ("bin/godot" + $buildInfo.PROGSUFFIX)
    if (-not (Test-Path -LiteralPath $editor)) { throw "Build the native editor first: $editor" }
    $gluePath = Join-Path $projectRoot 'modules/mono/glue'
    $glueLog = Join-Path $projectRoot '.build/fastbuild/mono-glue.log'
    $glueErrorLog = Join-Path $projectRoot '.build/fastbuild/mono-glue-error.log'
    $glueProcess = Start-Process -FilePath $editor -ArgumentList @('--headless', '--generate-mono-glue', "`"$gluePath`"") -WindowStyle Hidden -PassThru -RedirectStandardOutput $glueLog -RedirectStandardError $glueErrorLog
    if (-not $glueProcess.WaitForExit(120000)) {
        Stop-Process -Id $glueProcess.Id -Force -ErrorAction SilentlyContinue
        throw "C# glue generation timed out. See $glueLog and $glueErrorLog."
    }
    if ($glueProcess.ExitCode -ne 0) { throw "C# glue generation failed (exit $($glueProcess.ExitCode))." }
    $assemblyArgs = @('modules/mono/build_scripts/build_assemblies.py', '--godot-output-dir', './bin', '--godot-platform', 'windows', '--precision', $buildInfo.precision)
    if (-not $buildInfo.deprecated) { $assemblyArgs += '--no-deprecated' }
    & $python @assemblyArgs
    if ($LASTEXITCODE -ne 0) { throw "C# assembly build failed (exit $LASTEXITCODE)." }
} finally { Pop-Location }
