set_xmakever("3.1.1")
set_project("egp-box2d-qualification")
add_rules("mode.debug", "mode.release")
includes("../../../misc/xmake/qualification.lua")

target("egp_box2d_upstream")
    set_kind("binary")
    set_default(false)
    set_languages("c17")
    set_targetdir("$(builddir)/bin")
    add_rules("egp.qualification.precise")
    add_deps("egp_qualification_box2d_shared")
    add_files("../../../thirdparty/box2d/test/*.c")
    add_includedirs("../../../thirdparty/box2d/src")
    add_tests("upstream", {run_timeout = 120000})
target_end()
