set_xmakever("3.1.1")
set_project("EGP")
set_version("4.8")
set_config("builddir", ".build/xmake-default")
set_languages("c11", "cxx17")
set_policy("build.jobgraph", true)
set_policy("build.ccache", true)

includes("build/xmake/options.lua")
includes("build/xmake/platforms/visionos.lua")
includes("build/xmake/swift_rules.lua")
-- Default-off module-scoped embedded RTC targets.
if os.isfile("modules/superpos/xmake.lua") then includes("modules/superpos/xmake.lua") end
includes("build/xmake/targets.lua")

for _, name in ipairs({"editor", "template_debug", "template_release"}) do
    target(name)
        set_kind("binary")
        set_default(name == "editor")
        on_load(function (target)
            import("build.xmake.engine", {rootdir = os.projectdir()}).load_program(target)
        end)
        after_link(function (target)
            import("build.xmake.engine", {rootdir = os.projectdir()}).finish_program(target)
        end)
    target_end()
end

target("console_wrapper")
    set_kind("binary")
    set_default(false)
    on_load(function (target)
        import("build.xmake.engine", {rootdir = os.projectdir()}).load_program(target, true)
    end)
target_end()

target("editor_bootstrap")
    set_kind("binary")
    set_default(false)
    on_load(function (target)
        import("build.xmake.engine", {rootdir = os.projectdir()}).load_bootstrap(target)
    end)
target_end()

target("engine_api")
    set_kind("phony")
    set_default(false)
    add_deps("editor_bootstrap")
    set_policy("build.fence", true)
    on_load(function (target)
        import("build.xmake.engine", {rootdir = os.projectdir()}).load_api(target)
    end)
    on_build(function (target)
        import("build.xmake.engine", {rootdir = os.projectdir()}).build_api(target)
    end)
target_end()

target("web_side_module")
    set_kind("binary")
    set_default(false)
    on_load(function (target)
        import("build.xmake.engine", {rootdir = os.projectdir()}).load_web_side(target)
    end)
target_end()
