#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

import native_extension_sdk
from SCons.Script import ARGUMENTS

sdk_env = env.Clone()
sdk_env["egp_cpp_bits"] = "32" if env["arch"] in ("x86_32", "arm32", "rv32", "wasm32") else "64"
sdk_env["egp_cpp_api"] = ARGUMENTS.get("egp_cpp_api")
sdk_sources = [File("#thirdparty/godot-cpp/binding_generator.py"), File("cpp_sdk/CMakeLists.txt")]
sdk_sources += Glob("#thirdparty/godot-cpp/include/godot_cpp/*/*")
sdk_sources += Glob("#thirdparty/godot-cpp/include/godot_cpp/*.hpp")
sdk_sources += Glob("#thirdparty/godot-cpp/src/*.cpp")
sdk_sources += Glob("#thirdparty/godot-cpp/src/*/*.cpp")
sdk_sources += Glob("#thirdparty/godot-cpp/gdextension/*")
sdk_sources += Glob("cpp_sdk/templates/*")
sdk_sources += Glob("cpp_sdk/tools/*")
sdk_sources += [
    File("native_extension_sdk.py"),
    File("#thirdparty/godot-cpp/make_interface_header.py"),
    File("#thirdparty/godot-cpp/LICENSE.md"),
    env.Value(env["precision"]),
    env.Value(sdk_env["egp_cpp_bits"]),
]
if sdk_env["egp_cpp_api"]:
    sdk_sources += [File(sdk_env["egp_cpp_api"])]
sdk_env.CommandNoCache("native_extension_sdk.gen.h", sdk_sources, sdk_env.Run(native_extension_sdk.build_header))

env.add_source_files(env.editor_sources, "*.cpp")
