"""SCons retains the build graph; FASTBuild compiles its dirty MSVC object batches.

Generators, scanners, resources, libraries and linking stay with SCons. Batches
only execute after all their dependencies have been built. SCons determines which
objects are dirty, so FASTBuild must compile every object in the submitted batch.
"""

from __future__ import annotations

import hashlib
import os
import shutil
import subprocess
import threading
from pathlib import Path

import SCons.Action
import SCons.Errors
import SCons.PathList
import SCons.Subst
import SCons.Tool.msvc

_build_lock = threading.Lock()


def directory_batch_key(action, env, target, source):
    # SCons unions implicit dependencies across every source in an executor.
    # A global batch therefore makes one private/generated header invalidate
    # thousands of unrelated objects. Keep flags isolated by environment and
    # limit that dependency union to a source directory.
    return id(action), id(env), source[0].dir.abspath


def bff_string(value):
    # BFF uses ^ to escape literal quotes, dollars and carets; backslashes are literal.
    return "'" + str(value).replace("^", "^^").replace("$", "^$").replace("'", "^'") + "'"


def bff_array(values):
    return "{ " + ", ".join(bff_string(value) for value in values) + " }"


def compiler_files(compiler):
    folder = Path(compiler).parent
    files = list(folder.glob("*.dll"))
    files.extend(folder.glob("*/clui.dll"))
    files.extend(folder.glob("mspdbsrv.exe"))
    for required in ("c1.dll", "c1xx.dll", "c2.dll"):
        if not (folder / required).is_file():
            raise SCons.Errors.UserError(f"FASTBuild compiler synchronization requires {folder / required}")
    return sorted(str(path) for path in files)


def make_bff(compiler, extra_files, workers, entries):
    lines = [
        "// Generated by EGP's SCons FASTBuild integration. Do not edit.",
        "Settings\n{",
        f"    .Workers = {bff_array(workers)}",
        "}",
        "Compiler('egp-msvc')\n{",
        f"    .Executable = {bff_string(compiler)}",
        "    .CompilerFamily = 'msvc'",
        f"    .ExtraFiles = {bff_array(extra_files)}",
        "    .AllowDistribution = true",
        "}",
    ]
    aliases = []
    for index, (target, source, options) in enumerate(entries):
        target, source = Path(target), Path(source)
        # SCons adds configuration suffixes and libjpeg adds _8/_12 variants.
        if not target.name.startswith(source.stem) or target.name == source.stem:
            raise SCons.Errors.UserError(f"Unsupported FASTBuild object name: {source} -> {target}")
        alias = f"object-{index}"
        aliases.append(alias)
        lines.extend([
            f"ObjectList('{alias}')\n{{",
            "    .Compiler = 'egp-msvc'",
            f"    .CompilerInputFiles = {bff_array([source])}",
            f"    .CompilerOutputPath = {bff_string(str(target.parent) + os.sep)}",
            f"    .CompilerOutputExtension = {bff_string(target.name[len(source.stem) :])}",
            f"    .CompilerOptions = {bff_string(options)}",
            "    .AllowDistribution = true",
            "}",
        ])
    lines.extend(["Alias('all')\n{", f"    .Targets = {bff_array(aliases)}", "}"])
    return "\n".join(lines) + "\n"


class CompileAction(SCons.Action.FunctionAction):
    def __init__(self, original, options):
        self.original = original
        self.options = options
        super().__init__(
            self.compile, dict(strfunction=self.describe, batch_key=directory_batch_key, targets="$CHANGED_TARGETS")
        )

    def get_presig(self, target, source, env, executor=None):
        # Retain the original command signature, including each module's flags.
        return self.original.get_contents(target, source, env) + b"egp-fastbuild-v1" + self.options.encode()

    def get_implicit_deps(self, target, source, env, executor=None):
        # Keep SCons' compiler executable tracking when replacing the action.
        return self.original.get_implicit_deps(target, source, env) + [env.File(__file__)]

    def describe(self, target, source, env, executor=None):
        return f"FASTBuild compiling batch ({len(source)} sources) ..."

    def execute(self, target, source, env, executor=None):
        if executor:
            changed = {str(node) for node in executor.get_lvars()["CHANGED_TARGETS"]}
            pairs = [
                (batch.targets[0], batch.sources[0]) for batch in executor.batches if str(batch.targets[0]) in changed
            ]
        else:
            pairs = list(zip(target, source))
        return self.compile_pairs(pairs, env)

    def compile(self, target, source, env):
        return self.compile_pairs(list(zip(target, source)), env)

    def compile_pairs(self, pairs, env):
        if not pairs:
            return 0
        # Batch working directory differs from the repo root so a root fbuild
        # entry point can invoke SCons without colliding with FASTBuild's mutex.
        root = Path(env.Dir("#").abspath)
        build_dir = root / ".build" / "fastbuild" / "batches"
        build_dir.mkdir(parents=True, exist_ok=True)
        entries = []
        for target, source in pairs:
            # Match SCons' TARGET.RDirs lookup, including the defining
            # SConscript's cwd (e.g. SDL's CPPPATH=['.']), and repositories.
            paths = SCons.PathList.PathList(env.get("CPPPATH", [])).subst_path(env, [target], [source])
            include_dirs = target.RDirs(paths)
            # Freeze /I strings: SCons otherwise displays Dir nodes relatively.
            absolute_env = env.Override({"_CPPINCFLAGS": ["/I" + path.abspath for path in include_dirs]})
            args = absolute_env.subst_list(self.options, target=[target], source=[source])[0]
            # Definitions such as mbedTLS's config header already contain MSVC
            # escapes. Re-escaping them with list2cmdline changes their value.
            options = " ".join(SCons.Subst.escape_list(args, env["ESCAPE"]))
            options = options.replace("/Fo%2", '/Fo"%2"').replace("%1", '"%1"')  # codespell:ignore fo
            # /Zi's shared compiler PDB is incompatible with remote compilation.
            if any(str(arg).lower() in ("/zi", "/clr", "/gl") or str(arg).lower().startswith("/yu") for arg in args):
                raise SCons.Errors.UserError(
                    "EGP FASTBuild requires /Z7 and no PCH, /clr or /GL. Disable fastbuild for this configuration."
                )
            entries.append((target.abspath, source.rfile().abspath, options))
        batch_id = hashlib.sha256("\n".join(entry[0] for entry in entries).encode()).hexdigest()[:20]
        config = build_dir / f"{batch_id}.bff"
        workers = [worker.strip() for worker in env["fastbuild_workers"].split(";") if worker.strip()]
        compiler = env["EGP_FASTBUILD_COMPILER"]
        content = make_bff(compiler, env["EGP_FASTBUILD_COMPILER_FILES"], workers, entries)
        command = [
            env["fastbuild_exe"],
            "-config",
            str(config),
            "-clean",
            "-noprogress",
            "-summary",
            f"-j{env.GetOption('num_jobs')}",
        ]
        if env["fastbuild_dist"]:
            command.append("-distverbose" if env["fastbuild_distverbose"] else "-dist")
        if env["fastbuild_forceremote"]:
            command.extend(["-dist", "-forceremote", "-nolocalrace"])
        process_env = dict(os.environ)
        process_env.update({str(key): str(value) for key, value in env["ENV"].items()})
        # One local compiler pool for the whole SCons invocation.
        with _build_lock:
            config.write_text(content, encoding="utf-8")
            try:
                result = subprocess.run(command, cwd=build_dir, env=process_env, timeout=1800)
            except subprocess.TimeoutExpired:
                print("FASTBuild compilation timed out after 1800 seconds.")
                return 1
        if result.returncode:
            return result.returncode
        missing = [entry[0] for entry in entries if not Path(entry[0]).is_file()]
        if missing:
            raise SCons.Errors.UserError(f"FASTBuild succeeded without producing expected objects: {missing}")
        return 0


def configure(env):
    if (
        os.name != "nt"
        or env.get("platform") != "windows"
        or env.get("use_mingw")
        or env.get("use_llvm")
        or env.get("arch") != "x86_64"
    ):
        raise SCons.Errors.UserError("EGP FASTBuild currently supports Windows x86_64 with MSVC.")
    if env.get("ninja") or env.get("compiledb"):
        raise SCons.Errors.UserError("Use fastbuild separately from ninja/compiledb.")
    if env.get("c_compiler_launcher") or env.get("cpp_compiler_launcher"):
        raise SCons.Errors.UserError("Compiler launchers cannot be combined with EGP FASTBuild.")
    executable = shutil.which(str(env["fastbuild_exe"]))
    if not executable:
        raise SCons.Errors.UserError("FASTBuild is missing. Run misc/scripts/build_egp.ps1 -Setup first.")
    env["fastbuild_exe"] = str(Path(executable).resolve())
    version = subprocess.check_output([executable, "-version"], text=True)
    if "FASTBuild v1.20 " not in version:
        raise SCons.Errors.UserError("EGP expects FASTBuild v1.20, matching the remote worker.")
    compiler = shutil.which(env.subst("$CC"), path=env["ENV"]["PATH"])
    if not compiler or Path(compiler).name.lower() != "cl.exe":
        raise SCons.Errors.UserError("EGP FASTBuild requires the MSVC cl.exe compiler.")
    env["EGP_FASTBUILD_COMPILER"] = compiler
    env["EGP_FASTBUILD_COMPILER_FILES"] = compiler_files(compiler)
    env["MSVC_BATCH"] = False
    static_obj, shared_obj = SCons.Tool.createObjBuilders(env)
    for builder, shared in ((static_obj, False), (shared_obj, True)):
        for suffixes, original, flags in (
            (
                SCons.Tool.msvc.CSuffixes,
                SCons.Tool.msvc.ShCAction if shared else SCons.Tool.msvc.CAction,
                "$SHCFLAGS $SHCCFLAGS" if shared else "$CFLAGS $CCFLAGS",
            ),
            (
                SCons.Tool.msvc.CXXSuffixes,
                SCons.Tool.msvc.ShCXXAction if shared else SCons.Tool.msvc.CXXAction,
                "$SHCXXFLAGS $SHCCFLAGS" if shared else "$CXXFLAGS $CCFLAGS",
            ),
        ):
            action = CompileAction(original, "/Fo%2 /c %1 " + flags + " $_CCCOMCOM")  # codespell:ignore fo
            for suffix in suffixes:
                builder.add_action(suffix, action)
    print(f"FASTBuild v1.20 enabled (workers: {env['fastbuild_workers']}, distribution: {env['fastbuild_dist']}).")
